version: '3.8'

services:
  demo-app:
    build: .
    container_name: app
    environment:
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
